include mk/var.mk
include mk/version.mk
include mk/dirs.mk
include mk/cross.mk
include mk/tool.mk
include mk/src.mk
include mk/esp.mk
include mk/all.mk
include mk/format.mk
include mk/rule.mk
include mk/doc.mk
include mk/ref.mk
include mk/install.mk
