set_property (
    TARGET ${CMAKE_PROJECT_NAME}
    APPEND PROPERTY ADDITIONAL_CLEAN_FILES
        ${CMAKE_INSTALL_PREFIX}/${BIN_OUTPUT_NAME}${CMAKE_EXECUTABLE_SUFFIX}
            ${CMAKE_BINARY_DIR}/${BIN_OUTPUT_NAME}${CMAKE_EXECUTABLE_SUFFIX}
        ${ELF} ${DFU}
        # ${CMAKE_BINARY_DIR}
)
